development:
  adapter: postgresql
  encoding: unicode
  database: word_generator_development
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: word_generator_test
  pool: 5
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: word_generator_production
  pool: 5
  username: postgres